[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "irspy"
version = "0.0.1"
authors = [
  { name="irs"},
]
description = "Library from irs ural"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/irsural/irspy"
"Bug Tracker" = "https://github.com/irsural/irspy/issues"
