# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'source_mode_form.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(395, 575)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.clb_list_combobox = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clb_list_combobox.sizePolicy().hasHeightForWidth())
        self.clb_list_combobox.setSizePolicy(sizePolicy)
        self.clb_list_combobox.setMinimumSize(QtCore.QSize(140, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.clb_list_combobox.setFont(font)
        self.clb_list_combobox.setObjectName("clb_list_combobox")
        self.gridLayout_2.addWidget(self.clb_list_combobox, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.firmware_info_label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.firmware_info_label.sizePolicy().hasHeightForWidth())
        self.firmware_info_label.setSizePolicy(sizePolicy)
        self.firmware_info_label.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.firmware_info_label.setFont(font)
        self.firmware_info_label.setText("")
        self.firmware_info_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.firmware_info_label.setObjectName("firmware_info_label")
        self.horizontalLayout_8.addWidget(self.firmware_info_label)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 1, 0, 1, 2)
        self.open_tstlan_button = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.open_tstlan_button.sizePolicy().hasHeightForWidth())
        self.open_tstlan_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.open_tstlan_button.setFont(font)
        self.open_tstlan_button.setObjectName("open_tstlan_button")
        self.gridLayout_2.addWidget(self.open_tstlan_button, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.control_box = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.control_box.setFont(font)
        self.control_box.setFlat(True)
        self.control_box.setObjectName("control_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.control_box)
        self.verticalLayout_2.setContentsMargins(-1, 5, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.errors_label = QtWidgets.QLabel(self.control_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.errors_label.sizePolicy().hasHeightForWidth())
        self.errors_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.errors_label.setFont(font)
        self.errors_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.errors_label.setObjectName("errors_label")
        self.horizontalLayout_7.addWidget(self.errors_label)
        self.errors_count_label = QtWidgets.QLabel(self.control_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.errors_count_label.sizePolicy().hasHeightForWidth())
        self.errors_count_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.errors_count_label.setFont(font)
        self.errors_count_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.errors_count_label.setObjectName("errors_count_label")
        self.horizontalLayout_7.addWidget(self.errors_count_label)
        self.errors_out_button = QtWidgets.QPushButton(self.control_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.errors_out_button.sizePolicy().hasHeightForWidth())
        self.errors_out_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.errors_out_button.setFont(font)
        self.errors_out_button.setObjectName("errors_out_button")
        self.horizontalLayout_7.addWidget(self.errors_out_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.frame = QtWidgets.QFrame(self.control_box)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.clb_state_label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clb_state_label.sizePolicy().hasHeightForWidth())
        self.clb_state_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.clb_state_label.setFont(font)
        self.clb_state_label.setScaledContents(False)
        self.clb_state_label.setObjectName("clb_state_label")
        self.verticalLayout_3.addWidget(self.clb_state_label)
        self.verticalLayout_2.addWidget(self.frame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.acv_radio = QtWidgets.QRadioButton(self.control_box)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.acv_radio.setFont(font)
        self.acv_radio.setChecked(False)
        self.acv_radio.setObjectName("acv_radio")
        self.buttonGroup = QtWidgets.QButtonGroup(Form)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.acv_radio)
        self.horizontalLayout.addWidget(self.acv_radio)
        self.aci_radio = QtWidgets.QRadioButton(self.control_box)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.aci_radio.setFont(font)
        self.aci_radio.setChecked(True)
        self.aci_radio.setObjectName("aci_radio")
        self.buttonGroup.addButton(self.aci_radio)
        self.horizontalLayout.addWidget(self.aci_radio)
        self.dci_radio = QtWidgets.QRadioButton(self.control_box)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dci_radio.setFont(font)
        self.dci_radio.setObjectName("dci_radio")
        self.buttonGroup.addButton(self.dci_radio)
        self.horizontalLayout.addWidget(self.dci_radio)
        self.dcv_radio = QtWidgets.QRadioButton(self.control_box)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dcv_radio.setFont(font)
        self.dcv_radio.setObjectName("dcv_radio")
        self.buttonGroup.addButton(self.dcv_radio)
        self.horizontalLayout.addWidget(self.dcv_radio)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.frequency_edit = QEditCopyButton(self.control_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frequency_edit.sizePolicy().hasHeightForWidth())
        self.frequency_edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.frequency_edit.setFont(font)
        self.frequency_edit.setObjectName("frequency_edit")
        self.gridLayout.addWidget(self.frequency_edit, 5, 0, 1, 1)
        self.amplitude_edit = QEditCopyButton(self.control_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amplitude_edit.sizePolicy().hasHeightForWidth())
        self.amplitude_edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.amplitude_edit.setFont(font)
        self.amplitude_edit.setStyleSheet("")
        self.amplitude_edit.setObjectName("amplitude_edit")
        self.gridLayout.addWidget(self.amplitude_edit, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.source_mode_radio = QtWidgets.QRadioButton(self.control_box)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.source_mode_radio.setFont(font)
        self.source_mode_radio.setChecked(True)
        self.source_mode_radio.setObjectName("source_mode_radio")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(Form)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.source_mode_radio)
        self.horizontalLayout_5.addWidget(self.source_mode_radio)
        self.fixed_mode_radio = QtWidgets.QRadioButton(self.control_box)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.fixed_mode_radio.setFont(font)
        self.fixed_mode_radio.setObjectName("fixed_mode_radio")
        self.buttonGroup_2.addButton(self.fixed_mode_radio)
        self.horizontalLayout_5.addWidget(self.fixed_mode_radio)
        self.detuning_radio = QtWidgets.QRadioButton(self.control_box)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.detuning_radio.setFont(font)
        self.detuning_radio.setObjectName("detuning_radio")
        self.buttonGroup_2.addButton(self.detuning_radio)
        self.horizontalLayout_5.addWidget(self.detuning_radio)
        self.gridLayout.addLayout(self.horizontalLayout_5, 6, 0, 1, 1)
        self.apply_frequency_button = QtWidgets.QPushButton(self.control_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apply_frequency_button.sizePolicy().hasHeightForWidth())
        self.apply_frequency_button.setSizePolicy(sizePolicy)
        self.apply_frequency_button.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.apply_frequency_button.setFont(font)
        self.apply_frequency_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.apply_frequency_button.setIcon(icon)
        self.apply_frequency_button.setIconSize(QtCore.QSize(35, 35))
        self.apply_frequency_button.setObjectName("apply_frequency_button")
        self.gridLayout.addWidget(self.apply_frequency_button, 5, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.control_box)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.apply_amplitude_button = QtWidgets.QPushButton(self.control_box)
        self.apply_amplitude_button.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.apply_amplitude_button.setFont(font)
        self.apply_amplitude_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/ok.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/ok.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/ok.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.apply_amplitude_button.setIcon(icon1)
        self.apply_amplitude_button.setIconSize(QtCore.QSize(35, 35))
        self.apply_amplitude_button.setFlat(False)
        self.apply_amplitude_button.setObjectName("apply_amplitude_button")
        self.gridLayout.addWidget(self.apply_amplitude_button, 3, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.control_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.fast_adc_label = QtWidgets.QLabel(self.control_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fast_adc_label.sizePolicy().hasHeightForWidth())
        self.fast_adc_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.fast_adc_label.setFont(font)
        self.fast_adc_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.fast_adc_label.setObjectName("fast_adc_label")
        self.horizontalLayout_3.addWidget(self.fast_adc_label)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.enable_button = QtWidgets.QPushButton(self.control_box)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.enable_button.setFont(font)
        self.enable_button.setStyleSheet("")
        self.enable_button.setIconSize(QtCore.QSize(25, 25))
        self.enable_button.setCheckable(True)
        self.enable_button.setAutoDefault(True)
        self.enable_button.setObjectName("enable_button")
        self.verticalLayout_2.addWidget(self.enable_button)
        self.verticalLayout.addWidget(self.control_box)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_7.setText(_translate("Form", "Прошивка:"))
        self.open_tstlan_button.setText(_translate("Form", "Открыть tstlan"))
        self.control_box.setTitle(_translate("Form", "Управление"))
        self.errors_label.setText(_translate("Form", "Ошибки:"))
        self.errors_count_label.setText(_translate("Form", "0"))
        self.errors_out_button.setText(_translate("Form", "Вывести ошибки"))
        self.clb_state_label.setText(_translate("Form", "Остановлен"))
        self.acv_radio.setText(_translate("Form", "U~"))
        self.aci_radio.setText(_translate("Form", "I~"))
        self.dci_radio.setText(_translate("Form", "I="))
        self.dcv_radio.setText(_translate("Form", "U="))
        self.frequency_edit.setText(_translate("Form", "0"))
        self.amplitude_edit.setText(_translate("Form", "0"))
        self.source_mode_radio.setText(_translate("Form", "И"))
        self.fixed_mode_radio.setText(_translate("Form", "Ф"))
        self.detuning_radio.setText(_translate("Form", "Р"))
        self.label_6.setText(_translate("Form", "Частота, Гц"))
        self.label_5.setText(_translate("Form", "Амплитуда"))
        self.fast_adc_label.setText(_translate("Form", "(0)"))
        self.enable_button.setText(_translate("Form", "Пуск"))
from irspy.qt.custom_widgets.CustomLineEdit import QEditCopyButton
from irspy.qt.resources import icons
