# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'source_mode_widget.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_source_mode_widget(object):
    def setupUi(self, source_mode_widget):
        source_mode_widget.setObjectName("source_mode_widget")
        source_mode_widget.resize(376, 328)
        self.verticalLayout = QtWidgets.QVBoxLayout(source_mode_widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(source_mode_widget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.clb_state_label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clb_state_label.sizePolicy().hasHeightForWidth())
        self.clb_state_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.clb_state_label.setFont(font)
        self.clb_state_label.setScaledContents(False)
        self.clb_state_label.setObjectName("clb_state_label")
        self.horizontalLayout_4.addWidget(self.clb_state_label)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.clb_list_combobox = QtWidgets.QComboBox(source_mode_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clb_list_combobox.sizePolicy().hasHeightForWidth())
        self.clb_list_combobox.setSizePolicy(sizePolicy)
        self.clb_list_combobox.setMinimumSize(QtCore.QSize(140, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.clb_list_combobox.setFont(font)
        self.clb_list_combobox.setObjectName("clb_list_combobox")
        self.horizontalLayout_2.addWidget(self.clb_list_combobox)
        self.aci_radio = QtWidgets.QRadioButton(source_mode_widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.aci_radio.setFont(font)
        self.aci_radio.setChecked(True)
        self.aci_radio.setObjectName("aci_radio")
        self.buttonGroup = QtWidgets.QButtonGroup(source_mode_widget)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.aci_radio)
        self.horizontalLayout_2.addWidget(self.aci_radio)
        self.acv_radio = QtWidgets.QRadioButton(source_mode_widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.acv_radio.setFont(font)
        self.acv_radio.setChecked(False)
        self.acv_radio.setObjectName("acv_radio")
        self.buttonGroup.addButton(self.acv_radio)
        self.horizontalLayout_2.addWidget(self.acv_radio)
        self.dci_radio = QtWidgets.QRadioButton(source_mode_widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dci_radio.setFont(font)
        self.dci_radio.setObjectName("dci_radio")
        self.buttonGroup.addButton(self.dci_radio)
        self.horizontalLayout_2.addWidget(self.dci_radio)
        self.dcv_radio = QtWidgets.QRadioButton(source_mode_widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dcv_radio.setFont(font)
        self.dcv_radio.setObjectName("dcv_radio")
        self.buttonGroup.addButton(self.dcv_radio)
        self.horizontalLayout_2.addWidget(self.dcv_radio)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.amplitude_edit = QEditCopyButton(source_mode_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amplitude_edit.sizePolicy().hasHeightForWidth())
        self.amplitude_edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.amplitude_edit.setFont(font)
        self.amplitude_edit.setStyleSheet("")
        self.amplitude_edit.setObjectName("amplitude_edit")
        self.gridLayout.addWidget(self.amplitude_edit, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(source_mode_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.frequency_edit = QEditCopyButton(source_mode_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frequency_edit.sizePolicy().hasHeightForWidth())
        self.frequency_edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.frequency_edit.setFont(font)
        self.frequency_edit.setObjectName("frequency_edit")
        self.gridLayout.addWidget(self.frequency_edit, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.source_mode_radio = QtWidgets.QRadioButton(source_mode_widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.source_mode_radio.setFont(font)
        self.source_mode_radio.setChecked(True)
        self.source_mode_radio.setObjectName("source_mode_radio")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(source_mode_widget)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.source_mode_radio)
        self.horizontalLayout_5.addWidget(self.source_mode_radio)
        self.fixed_mode_radio = QtWidgets.QRadioButton(source_mode_widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.fixed_mode_radio.setFont(font)
        self.fixed_mode_radio.setObjectName("fixed_mode_radio")
        self.buttonGroup_2.addButton(self.fixed_mode_radio)
        self.horizontalLayout_5.addWidget(self.fixed_mode_radio)
        self.detuning_radio = QtWidgets.QRadioButton(source_mode_widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.detuning_radio.setFont(font)
        self.detuning_radio.setObjectName("detuning_radio")
        self.buttonGroup_2.addButton(self.detuning_radio)
        self.horizontalLayout_5.addWidget(self.detuning_radio)
        self.gridLayout.addLayout(self.horizontalLayout_5, 4, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(source_mode_widget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.apply_amplitude_button = QtWidgets.QPushButton(source_mode_widget)
        self.apply_amplitude_button.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.apply_amplitude_button.setFont(font)
        self.apply_amplitude_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/ok.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/ok.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/ok.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.apply_amplitude_button.setIcon(icon)
        self.apply_amplitude_button.setIconSize(QtCore.QSize(35, 35))
        self.apply_amplitude_button.setFlat(False)
        self.apply_amplitude_button.setObjectName("apply_amplitude_button")
        self.gridLayout.addWidget(self.apply_amplitude_button, 1, 1, 1, 1)
        self.apply_frequency_button = QtWidgets.QPushButton(source_mode_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apply_frequency_button.sizePolicy().hasHeightForWidth())
        self.apply_frequency_button.setSizePolicy(sizePolicy)
        self.apply_frequency_button.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.apply_frequency_button.setFont(font)
        self.apply_frequency_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.apply_frequency_button.setIcon(icon1)
        self.apply_frequency_button.setIconSize(QtCore.QSize(35, 35))
        self.apply_frequency_button.setObjectName("apply_frequency_button")
        self.gridLayout.addWidget(self.apply_frequency_button, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.enable_button = QtWidgets.QPushButton(source_mode_widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.enable_button.setFont(font)
        self.enable_button.setIconSize(QtCore.QSize(25, 25))
        self.enable_button.setCheckable(True)
        self.enable_button.setObjectName("enable_button")
        self.verticalLayout.addWidget(self.enable_button)

        self.retranslateUi(source_mode_widget)
        QtCore.QMetaObject.connectSlotsByName(source_mode_widget)

    def retranslateUi(self, source_mode_widget):
        _translate = QtCore.QCoreApplication.translate
        source_mode_widget.setWindowTitle(_translate("source_mode_widget", "Form"))
        self.label_4.setText(_translate("source_mode_widget", "Статус:"))
        self.clb_state_label.setText(_translate("source_mode_widget", "Остановлен"))
        self.aci_radio.setText(_translate("source_mode_widget", "I~"))
        self.acv_radio.setText(_translate("source_mode_widget", "U~"))
        self.dci_radio.setText(_translate("source_mode_widget", "I="))
        self.dcv_radio.setText(_translate("source_mode_widget", "U="))
        self.amplitude_edit.setText(_translate("source_mode_widget", "0"))
        self.label_5.setText(_translate("source_mode_widget", "Амплитуда"))
        self.frequency_edit.setText(_translate("source_mode_widget", "0"))
        self.source_mode_radio.setText(_translate("source_mode_widget", "Источник"))
        self.fixed_mode_radio.setText(_translate("source_mode_widget", "Фиксир."))
        self.detuning_radio.setText(_translate("source_mode_widget", "Расстройка"))
        self.label_6.setText(_translate("source_mode_widget", "Частота, Гц"))
        self.enable_button.setText(_translate("source_mode_widget", "Старт"))
from irspy.qt.custom_widgets.CustomLineEdit import QEditCopyButton
from irspy.qt.resources import icons
